name: CI
on:
  push:
    branches:
      - hexo
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v1
        with:
          ref: hexo

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Set Env
        env: 
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}  
        run: |
          git config --global user.email "elepher.ai@gmail.com"
          git config --global user.name "elepher ai"
          sed -i "s/GITHUB_ACCESS_TOKEN/$GITHUB_ACCESS_TOKEN/g" ./_config.fluid.yml

      - name: Hexo
        run: |
          npm i -g hexo-cli
          npm i
          hexo clean && hexo g && hexo d